name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install ruff mypy
      - run: ruff check ruby/ tests/
      - run: mypy ruby/ --ignore-missing-imports

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install mock dependencies
        run: |
          pip install pytest pytest-mock numpy pyyaml
          # mock hardware libs not available on CI
          pip install RPi.GPIO==0.7.1 --no-deps || true
      - run: pytest tests/unit/ -v --tb=short

  build-check:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install build
      - run: python -m build --no-isolation || true
      - run: python -c "import ruby.memory.store; print('import OK')"
        env:
          PYTHONPATH: .
